name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkgconf libpcsclite-dev softhsm2 libsofthsm2 help2man openjdk-8-jdk maven ant opensc
    - uses: actions/checkout@v4
    - name: Setup jcardsim
      run: |
        cd jcardsim
        mvn initialize
        mvn clean install
    - name: Setup virtualsmartcard
      run: |
        cd vsmartcard/virtualsmartcard
        autoreconf -vis
        ./configure
        sudo make install
    - name: Setup pivapplet
      run: |
        javac -classpath jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar PivApplet/src/net/cooperi/pivapplet/*.java
    - name: Build pivapplet
      run: |
        cd PivApplet
        ant
    - name: Install system dependencies2
      run: |
        cargo install wasm-pack
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
