name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkgconf libpcsclite-dev softhsm2 libsofthsm2 help2man openjdk-8-jdk maven ant opensc pcscd pcsc-tools libpcsclite-dev
        sudo apt-get install libtool libltdl-dev autoconf automake autoconf-archive libjson-c-dev libtpms0 libtss2-tcti-libtpms0t64
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Java 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Setup jcardsim
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 3
        command: |
          export JC_CLASSIC_HOME=$PWD/javacard-sdk/jc305u3_kit
          export JC_HOME=$PWD/javacard-sdk/jc305u3_kit
          cd jcardsim
          mvn initialize
          mvn clean install
    - name: Setup virtualsmartcard
      run: |
        export JC_CLASSIC_HOME=$PWD/javacard-sdk/jc305u3_kit
        export JC_HOME=$PWD/javacard-sdk/jc305u3_kit
        cd vsmartcard/virtualsmartcard
        autoreconf -vis
        ./configure
        sudo make install
    - name: Setup pivapplet
      run: |
        export JC_CLASSIC_HOME=$PWD/javacard-sdk/jc305u3_kit
        export JC_HOME=$PWD/javacard-sdk/jc305u3_kit
        javac -classpath jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar PivApplet/src/net/cooperi/pivapplet/*.java
    - name: Build pivapplet
      run: |
        export JC_CLASSIC_HOME=$PWD/javacard-sdk/jc305u3_kit
        export JC_HOME=$PWD/javacard-sdk/jc305u3_kit
        cd PivApplet
        ant
    - name: Install system dependencies2
      run: |
        cargo install wasm-pack
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: |
        export PCSCD_DEBUG="-d -a"
        . .github/restart-pcscd.sh
        cargo test --verbose
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Generate code coverage
      run: |
        export PCSCD_DEBUG="-d -a"
        . .github/restart-pcscd.sh
        cargo clean
        cargo llvm-cov --all-features --codecov --output-path codecov.json
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: codecov.json
        fail_ci_if_error: true

