name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkgconf libpcsclite-dev softhsm2 libsofthsm2 help2man openjdk-8-jdk maven ant opensc
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Java 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Setup jcardsim
      run: |
        export JC_CLASSIC_HOME=$PWD/javacard-sdk/jc305u3_kit
        export JC_HOME=$PWD/javacard-sdk/jc305u3_kit
        cd jcardsim
        mvn initialize
        mvn clean install
    - name: Setup virtualsmartcard
      run: |
        export JC_CLASSIC_HOME=$PWD/javacard-sdk/jc305u3_kit
        export JC_HOME=$PWD/javacard-sdk/jc305u3_kit
        cd vsmartcard/virtualsmartcard
        autoreconf -vis
        ./configure
        sudo make install
    - name: Setup pivapplet
      run: |
        export JC_CLASSIC_HOME=$PWD/javacard-sdk/jc305u3_kit
        export JC_HOME=$PWD/javacard-sdk/jc305u3_kit
        javac -classpath jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar PivApplet/src/net/cooperi/pivapplet/*.java
    - name: Build pivapplet
      run: |
        export JC_CLASSIC_HOME=$PWD/javacard-sdk/jc305u3_kit
        export JC_HOME=$PWD/javacard-sdk/jc305u3_kit
        cd PivApplet
        ant
    - name: Install system dependencies2
      run: |
        cargo install wasm-pack
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
